"""distribution

Revision ID: 2d48dcc5cdef
Revises: 8175d4cdce16
Create Date: 2026-10-01 14:25:27.019497
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.types

revision: str = '2d48dcc5cdef'
down_revision: str | None = '8175d4cdce16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor_levels',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distributor_levels_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributor_levels')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_distributor_levels_tenant_id_code'))
    )
    op.create_index(op.f('ix_distributor_levels_tenant_id'), 'distributor_levels', ['tenant_id'], unique=False)
    op.create_table('distributors',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('level_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('allow_dropship', sa.Boolean(), nullable=False),
    sa.Column('allow_wholesale', sa.Boolean(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('sales_rep_id', sa.BigInteger(), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['distributor_levels.id'], name=op.f('fk_distributors_level_id_distributor_levels')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_distributors_shop_id_shops')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distributors_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributors')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_distributors_tenant_id_code'))
    )
    op.create_index(op.f('ix_distributors_api_key_prefix'), 'distributors', ['api_key_prefix'], unique=False)
    op.create_index(op.f('ix_distributors_status'), 'distributors', ['status'], unique=False)
    op.create_index(op.f('ix_distributors_tenant_id'), 'distributors', ['tenant_id'], unique=False)
    op.create_table('distribution_level_prices',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['distributor_levels.id'], name=op.f('fk_distribution_level_prices_level_id_distributor_levels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_distribution_level_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distribution_level_prices_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distribution_level_prices')),
    sa.UniqueConstraint('product_id', 'level_id', name=op.f('uq_distribution_level_prices_product_id_level_id'))
    )
    op.create_index(op.f('ix_distribution_level_prices_level_id'), 'distribution_level_prices', ['level_id'], unique=False)
    op.create_index(op.f('ix_distribution_level_prices_product_id'), 'distribution_level_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_distribution_level_prices_tenant_id'), 'distribution_level_prices', ['tenant_id'], unique=False)
    op.create_table('distribution_products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock_display', sa.String(length=16), nullable=False),
    sa.Column('stock_cap', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_distribution_products_product_id_products')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distribution_products_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distribution_products')),
    sa.UniqueConstraint('tenant_id', 'product_id', name=op.f('uq_distribution_products_tenant_id_product_id'))
    )
    op.create_index(op.f('ix_distribution_products_is_active'), 'distribution_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_distribution_products_product_id'), 'distribution_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_distribution_products_tenant_id'), 'distribution_products', ['tenant_id'], unique=False)
    op.create_table('distributor_recharges',
    sa.Column('request_no', sa.String(length=32), nullable=False),
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('transaction_no', sa.String(length=64), nullable=True),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', app.core.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('fk_distributor_recharges_distributor_id_distributors')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distributor_recharges_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributor_recharges')),
    sa.UniqueConstraint('tenant_id', 'request_no', name=op.f('uq_distributor_recharges_tenant_id_request_no'))
    )
    op.create_index(op.f('ix_distributor_recharges_distributor_id'), 'distributor_recharges', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_distributor_recharges_status'), 'distributor_recharges', ['status'], unique=False)
    op.create_index(op.f('ix_distributor_recharges_tenant_id'), 'distributor_recharges', ['tenant_id'], unique=False)
    op.create_table('distributor_transactions',
    sa.Column('distributor_id', sa.BigInteger(), nullable=False),
    sa.Column('txn_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('ref_no', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('fk_distributor_transactions_distributor_id_distributors')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_distributor_transactions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributor_transactions'))
    )
    op.create_index(op.f('ix_distributor_transactions_distributor_id'), 'distributor_transactions', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_distributor_transactions_ref_no'), 'distributor_transactions', ['ref_no'], unique=False)
    op.create_index(op.f('ix_distributor_transactions_tenant_id'), 'distributor_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_distributor_transactions_txn_type'), 'distributor_transactions', ['txn_type'], unique=False)
    with op.batch_alter_table('sales_orders') as batch_op:
        batch_op.add_column(sa.Column('distributor_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('distribution_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('charge_detail', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_orders_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_orders_distributor_id_distributors'), 'distributors', ['distributor_id'], ['id'])
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=16), server_default='staff', nullable=False))
        batch_op.add_column(sa.Column('distributor_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_type'), ['user_type'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_distributor_id_distributors'), 'distributors', ['distributor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_distributor_id_distributors'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_user_type'))
        batch_op.drop_index(batch_op.f('ix_users_distributor_id'))
        batch_op.drop_column('distributor_id')
        batch_op.drop_column('user_type')
    with op.batch_alter_table('sales_orders') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_orders_distributor_id_distributors'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_orders_distributor_id'))
        batch_op.drop_column('charge_detail')
        batch_op.drop_column('distribution_type')
        batch_op.drop_column('distributor_id')
    op.drop_index(op.f('ix_distributor_transactions_txn_type'), table_name='distributor_transactions')
    op.drop_index(op.f('ix_distributor_transactions_tenant_id'), table_name='distributor_transactions')
    op.drop_index(op.f('ix_distributor_transactions_ref_no'), table_name='distributor_transactions')
    op.drop_index(op.f('ix_distributor_transactions_distributor_id'), table_name='distributor_transactions')
    op.drop_table('distributor_transactions')
    op.drop_index(op.f('ix_distributor_recharges_tenant_id'), table_name='distributor_recharges')
    op.drop_index(op.f('ix_distributor_recharges_status'), table_name='distributor_recharges')
    op.drop_index(op.f('ix_distributor_recharges_distributor_id'), table_name='distributor_recharges')
    op.drop_table('distributor_recharges')
    op.drop_index(op.f('ix_distribution_products_tenant_id'), table_name='distribution_products')
    op.drop_index(op.f('ix_distribution_products_product_id'), table_name='distribution_products')
    op.drop_index(op.f('ix_distribution_products_is_active'), table_name='distribution_products')
    op.drop_table('distribution_products')
    op.drop_index(op.f('ix_distribution_level_prices_tenant_id'), table_name='distribution_level_prices')
    op.drop_index(op.f('ix_distribution_level_prices_product_id'), table_name='distribution_level_prices')
    op.drop_index(op.f('ix_distribution_level_prices_level_id'), table_name='distribution_level_prices')
    op.drop_table('distribution_level_prices')
    op.drop_index(op.f('ix_distributors_tenant_id'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_status'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_api_key_prefix'), table_name='distributors')
    op.drop_table('distributors')
    op.drop_index(op.f('ix_distributor_levels_tenant_id'), table_name='distributor_levels')
    op.drop_table('distributor_levels')
    # ### end Alembic commands ###
