"""fulfillment waves and product barcode

Revision ID: 45da6463832a
Revises: 2d48dcc5cdef
Create Date: 2026-10-01 14:57:10.863383
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.types

revision: str = '45da6463832a'
down_revision: str | None = '2d48dcc5cdef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_waves',
    sa.Column('wave_no', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('sku_count', sa.Integer(), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('picker_id', sa.BigInteger(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('picked_at', app.core.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_pick_waves_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_pick_waves_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pick_waves'))
    )
    op.create_index(op.f('ix_pick_waves_status'), 'pick_waves', ['status'], unique=False)
    op.create_index(op.f('ix_pick_waves_tenant_id'), 'pick_waves', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pick_waves_warehouse_id'), 'pick_waves', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_pick_waves_wave_no'), 'pick_waves', ['wave_no'], unique=False)
    op.add_column('products', sa.Column('barcode', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    with op.batch_alter_table('sales_orders') as batch_op:
        batch_op.add_column(sa.Column('wave_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_orders_wave_id'), ['wave_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_orders_wave_id_pick_waves'), 'pick_waves', ['wave_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_orders_wave_id_pick_waves'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_orders_wave_id'))
        batch_op.drop_column('wave_id')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'barcode')
    op.drop_index(op.f('ix_pick_waves_wave_no'), table_name='pick_waves')
    op.drop_index(op.f('ix_pick_waves_warehouse_id'), table_name='pick_waves')
    op.drop_index(op.f('ix_pick_waves_tenant_id'), table_name='pick_waves')
    op.drop_index(op.f('ix_pick_waves_status'), table_name='pick_waves')
    op.drop_table('pick_waves')
    # ### end Alembic commands ###
