"""approval flows and assembly orders

Revision ID: 39bd6ae67159
Revises: 45da6463832a
Create Date: 2026-10-01 15:11:23.340781
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.types

revision: str = '39bd6ae67159'
down_revision: str | None = '45da6463832a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_flows',
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_flows_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_flows'))
    )
    op.create_index(op.f('ix_approval_flows_doc_type'), 'approval_flows', ['doc_type'], unique=False)
    op.create_index(op.f('ix_approval_flows_tenant_id'), 'approval_flows', ['tenant_id'], unique=False)
    op.create_table('approval_instances',
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_no', sa.String(length=64), nullable=True),
    sa.Column('flow_id', sa.BigInteger(), nullable=True),
    sa.Column('flow_name', sa.String(length=64), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('amount_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('submitter_name', sa.String(length=64), nullable=True),
    sa.Column('finished_at', app.core.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flows.id'], name=op.f('fk_approval_instances_flow_id_approval_flows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_instances_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_instances'))
    )
    op.create_index('ix_approval_instances_doc', 'approval_instances', ['doc_type', 'doc_id'], unique=False)
    op.create_index(op.f('ix_approval_instances_status'), 'approval_instances', ['status'], unique=False)
    op.create_index(op.f('ix_approval_instances_tenant_id'), 'approval_instances', ['tenant_id'], unique=False)
    op.create_table('approval_records',
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['approval_instances.id'], name=op.f('fk_approval_records_instance_id_approval_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_records_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    op.create_index(op.f('ix_approval_records_instance_id'), 'approval_records', ['instance_id'], unique=False)
    op.create_index(op.f('ix_approval_records_tenant_id'), 'approval_records', ['tenant_id'], unique=False)
    op.create_table('assembly_orders',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=True),
    sa.Column('completed_at', app.core.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.BigInteger(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_assembly_orders_product_id_products')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assembly_orders_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_assembly_orders_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assembly_orders'))
    )
    op.create_index(op.f('ix_assembly_orders_order_no'), 'assembly_orders', ['order_no'], unique=False)
    op.create_index(op.f('ix_assembly_orders_product_id'), 'assembly_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_assembly_orders_status'), 'assembly_orders', ['status'], unique=False)
    op.create_index(op.f('ix_assembly_orders_tenant_id'), 'assembly_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assembly_orders_warehouse_id'), 'assembly_orders', ['warehouse_id'], unique=False)
    op.create_table('assembly_lines',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_per_unit', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['assembly_orders.id'], name=op.f('fk_assembly_lines_order_id_assembly_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_assembly_lines_product_id_products')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assembly_lines_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assembly_lines'))
    )
    op.create_index(op.f('ix_assembly_lines_order_id'), 'assembly_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_assembly_lines_tenant_id'), 'assembly_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assembly_lines_tenant_id'), table_name='assembly_lines')
    op.drop_index(op.f('ix_assembly_lines_order_id'), table_name='assembly_lines')
    op.drop_table('assembly_lines')
    op.drop_index(op.f('ix_assembly_orders_warehouse_id'), table_name='assembly_orders')
    op.drop_index(op.f('ix_assembly_orders_tenant_id'), table_name='assembly_orders')
    op.drop_index(op.f('ix_assembly_orders_status'), table_name='assembly_orders')
    op.drop_index(op.f('ix_assembly_orders_product_id'), table_name='assembly_orders')
    op.drop_index(op.f('ix_assembly_orders_order_no'), table_name='assembly_orders')
    op.drop_table('assembly_orders')
    op.drop_index(op.f('ix_approval_records_tenant_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_instance_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_approval_instances_tenant_id'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_status'), table_name='approval_instances')
    op.drop_index('ix_approval_instances_doc', table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index(op.f('ix_approval_flows_tenant_id'), table_name='approval_flows')
    op.drop_index(op.f('ix_approval_flows_doc_type'), table_name='approval_flows')
    op.drop_table('approval_flows')
    # ### end Alembic commands ###
